packages:
  - apps/*
  - packages/*

allowBuilds:
  '@google/genai': true
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: true
  protobufjs: false

peerDependencyRules:
  ignoreMissing:
    - '@types/better-sqlite3'
    - better-sqlite3
